"""
AI Business Report Visual Integrator + PDF Generator

Reads:
    output/ai_business_report.md
    output/visualization_plan.json
    output/visualization_validation.json
    output/visualizations/*.png

Generates:
    output/ai_business_report_with_visuals.md
    output/ai_business_report_final.pdf

The original Markdown report is preserved.
"""

import json
import html
import re
import sys
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image,
    Table,
    TableStyle,
    KeepTogether
)


# ============================================================
# PATHS
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BASE_DIR / "output"

REPORT_FILE = OUTPUT_DIR / "ai_business_report.md"

VISUALIZATION_PLAN_FILE = (
    OUTPUT_DIR / "visualization_plan.json"
)

VISUALIZATION_VALIDATION_FILE = (
    OUTPUT_DIR / "visualization_validation.json"
)

FINAL_REPORT_FILE = (
    OUTPUT_DIR / "ai_business_report_with_visuals.md"
)

FINAL_PDF_FILE = (
    OUTPUT_DIR / "ai_business_report_final.pdf"
)

VISUALIZATION_DIR = (
    OUTPUT_DIR / "visualizations"
)


# ============================================================
# LOAD FILES
# ============================================================

def load_report(file_path: Path) -> str:
    """Load Markdown report."""

    if not file_path.exists():
        raise FileNotFoundError(
            f"Report file not found: {file_path}"
        )

    return file_path.read_text(
        encoding="utf-8"
    )


def load_json(file_path: Path) -> dict:
    """Load JSON file."""

    if not file_path.exists():
        raise FileNotFoundError(
            f"JSON file not found: {file_path}"
        )

    with open(
        file_path,
        "r",
        encoding="utf-8"
    ) as file:

        return json.load(file)


# ============================================================
# MARKDOWN CLEANUP
# ============================================================

def clean_markdown_formatting(report: str) -> str:
    """
    Normalize escaped Markdown characters
    generated by the AI report.
    """

    report = re.sub(
        r"(?m)^\\\*",
        "*",
        report
    )

    report = re.sub(
        r"(?m)^([0-9]+)\\\.",
        r"\1.",
        report
    )

    report = re.sub(
        r"(?m)^\\---$",
        "---",
        report
    )

    report = report.replace(
        r"\(",
        "("
    )

    report = report.replace(
        r"\)",
        ")"
    )

    report = report.replace(
        r"\_",
        "_"
    )

    report = report.replace(
        r"\*\*",
        "**"
    )

    report = report.replace(
        r"\`",
        "`"
    )

    report = re.sub(
        r"(?m)^\\\s+",
        "",
        report
    )

    report = re.sub(
        r"\n{4,}",
        "\n\n\n",
        report
    )

    return report


# ============================================================
# VALIDATION
# ============================================================

def check_validation(validation: dict):

    status = validation.get(
        "status",
        "UNKNOWN"
    )

    print(
        f"Validation status: {status}"
    )

    if status != "SAFE_TO_GENERATE":

        raise RuntimeError(
            "Visualization validation failed. "
            f"Status: {status}"
        )

    print(
        "✓ Visualization validation passed."
    )


# ============================================================
# VISUALIZATION FILE NAME
# ============================================================

def resolve_visualization_filename(
    visualization: dict,
    index: int
) -> str:

    filename = visualization.get(
        "filename"
    )

    if filename:
        return filename

    filename = visualization.get(
        "output_file"
    )

    if filename:
        return filename

    title = visualization.get(
        "title",
        f"Visualization {index}"
    )

    safe_title = re.sub(
        r"[^a-z0-9]+",
        "_",
        title.lower()
    ).strip("_")

    return (
        f"{index:02d}_"
        f"{safe_title}.png"
    )


# ============================================================
# CHECK VISUALIZATION FILES
# ============================================================

def check_visualization_files(
    plan: dict
):

    visualizations = plan.get(
        "visualizations",
        []
    )

    if not visualizations:

        raise ValueError(
            "No visualizations found in visualization plan."
        )

    print(
        f"✓ Found {len(visualizations)} visualizations."
    )

    missing_files = []

    for index, visualization in enumerate(
        visualizations,
        start=1
    ):

        filename = (
            resolve_visualization_filename(
                visualization,
                index
            )
        )

        file_path = (
            VISUALIZATION_DIR / filename
        )

        if file_path.exists():

            print(
                f"  ✓ {filename}"
            )

        else:

            print(
                f"  ✗ {filename}"
            )

            missing_files.append(
                filename
            )

    if missing_files:

        raise FileNotFoundError(
            "Missing visualization files:\n"
            + "\n".join(missing_files)
        )

    print(
        "✓ All visualization files verified."
    )


# ============================================================
# REMOVE H1 SECTION
# ============================================================

def remove_h1_section(
    report: str,
    section_name: str
) -> str:
    """
    Remove a complete H1 Markdown section,
    including its content, until the next H1.
    """

    section_pattern = (
        rf"(?ms)^#\s+"
        rf"{re.escape(section_name)}"
        rf"\s*$.*?"
        rf"(?=^#\s+|\Z)"
    )

    return re.sub(
        section_pattern,
        "",
        report
    )


# ============================================================
# REMOVE OLD VISUALIZATION BLOCKS
# ============================================================

def remove_existing_visualization_blocks(
    report: str
) -> str:
    """
    Remove old visualization blocks and legacy
    volume-based analysis sections.

    The current sanitized dataset is revenue-focused,
    therefore legacy transaction-volume sections must
    not remain in the final report.
    """

    # --------------------------------------------------------
    # Remove Markdown image blocks
    # --------------------------------------------------------

    report = re.sub(
        r"(?m)^!\[[^\]]*\]\(visualizations/[^)]*\)\s*\n?",
        "",
        report,
        flags=re.IGNORECASE
    )

    # --------------------------------------------------------
    # Remove old visualization headings
    # --------------------------------------------------------

    visualization_titles = [
        "Daily Revenue Trend by Service",
        "Top Services by Total Revenue",
        "Total Revenue by Service",
        "Daily Revenue Intensity Heatmap by Service",
        "Total Transaction Volume by Service",
        "Total Revenue vs. Transaction Volume",
        "Total Revenue vs Transaction Volume"
    ]

    for title in visualization_titles:

        pattern = (
            r"(?m)^###\s+"
            + re.escape(title)
            + r"\s*\n?"
        )

        report = re.sub(
            pattern,
            "",
            report,
            flags=re.IGNORECASE
        )

    # --------------------------------------------------------
    # Remove legacy Revenue vs Volume H1 section
    # --------------------------------------------------------

    report = remove_h1_section(
        report,
        "Revenue vs Volume"
    )

    # --------------------------------------------------------
    # Remove legacy volume-related paragraphs
    # --------------------------------------------------------

    volume_patterns = [

        r"(?is)"
        r"•?\s*Volume Metrics Status:.*?"
        r"(?=\n\s*(?:•|[-*]|\d+\.|$))",

        r"(?is)"
        r"•?\s*Rank Comparisons:.*?"
        r"(?=\n\s*(?:•|[-*]|\d+\.|$))",

        r"(?is)"
        r"•?\s*Analytical Boundary:.*?"
        r"(?=\n\s*(?:•|[-*]|\d+\.|$))",
    ]

    for pattern in volume_patterns:

        report = re.sub(
            pattern,
            "",
            report
        )

    # --------------------------------------------------------
    # Remove legacy limitation specifically about volume
    # --------------------------------------------------------

    report = re.sub(
        r"(?is)"
        r"\d+\.\s*Absence of Transaction Volume Data:"
        r".*?"
        r"(?=\n\s*\d+\.\s|\Z)",
        "",
        report
    )

    # --------------------------------------------------------
    # Cleanup
    # --------------------------------------------------------

    report = re.sub(
        r"\n{4,}",
        "\n\n\n",
        report
    )

    return report


# ============================================================
# TITLE NORMALIZATION
# ============================================================

def normalize_title(title: str) -> str:

    return title.strip().rstrip(".")


# ============================================================
# VISUALIZATION MARKDOWN
# ============================================================

def build_visualization_markdown(
    visualization: dict,
    index: int
) -> str:

    title = normalize_title(
        visualization.get(
            "title",
            f"Visualization {index}"
        )
    )

    filename = (
        resolve_visualization_filename(
            visualization,
            index
        )
    )

    relative_path = (
        f"visualizations/{filename}"
    )

    return (
        f"### {title}\n\n"
        f"![{title}]({relative_path})\n\n"
    )


# ============================================================
# SECTION DETECTION
# ============================================================

def get_section_for_visualization(
    title: str
):

    title_lower = title.lower().strip()

    if (
        "daily revenue trend by service"
        in title_lower
    ):

        return "Time Trend Analysis"

    if (
        "top services by total revenue"
        in title_lower
        or
        "total revenue by service"
        in title_lower
        or
        "total transaction volume by service"
        in title_lower
        or
        "heatmap"
        in title_lower
    ):

        return "Service Performance"

    if (
        "total revenue vs"
        in title_lower
    ):

        return "Revenue vs Volume"

    return None


# ============================================================
# FIND H1 SECTION
# ============================================================

def find_h1_section(
    report: str,
    section_name: str
):

    section_pattern = (
        rf"(?m)^#\s+"
        rf"{re.escape(section_name)}"
        rf"\s*$"
    )

    match = re.search(
        section_pattern,
        report
    )

    if not match:
        return None

    section_start = match.end()

    next_section_match = re.search(
        r"(?m)^#\s+",
        report[section_start:]
    )

    if next_section_match:

        section_end = (
            section_start
            + next_section_match.start()
        )

    else:

        section_end = len(report)

    return (
        section_start,
        section_end
    )


# ============================================================
# INSERT VISUALIZATIONS
# ============================================================

def insert_visualizations_into_section(
    report: str,
    section_name: str,
    charts
):

    section_info = find_h1_section(
        report,
        section_name
    )

    if not section_info:

        print(
            f"  ⚠ Section not found: "
            f"{section_name}"
        )

        return report, 0

    section_start, section_end = (
        section_info
    )

    section_content = report[
        section_start:section_end
    ]

    inserted_count = 0

    for title, chart_markdown in charts:

        if chart_markdown.strip() in section_content:
            continue

        section_content = (
            section_content.rstrip()
            + "\n\n"
            + chart_markdown.strip()
            + "\n"
        )

        inserted_count += 1

    report = (
        report[:section_start]
        + "\n"
        + section_content.lstrip()
        + "\n"
        + report[section_end:]
    )

    return (
        report,
        inserted_count
    )


# ============================================================
# INTEGRATE VISUALIZATIONS
# ============================================================

def integrate_visualizations(
    report: str,
    plan: dict
):

    visualizations = plan.get(
        "visualizations",
        []
    )

    if not visualizations:

        raise ValueError(
            "No visualizations found in plan."
        )

    section_insertions = {}

    for index, visualization in enumerate(
        visualizations,
        start=1
    ):

        title = normalize_title(
            visualization.get(
                "title",
                f"Visualization {index}"
            )
        )

        section = (
            get_section_for_visualization(
                title
            )
        )

        if not section:

            print(
                f"  ⚠ No matching section "
                f"found for: {title}"
            )

            continue

        chart_markdown = (
            build_visualization_markdown(
                visualization,
                index
            )
        )

        section_insertions.setdefault(
            section,
            []
        ).append(
            (
                title,
                chart_markdown
            )
        )

    total_inserted = 0

    for section, charts in (
        section_insertions.items()
    ):

        print(
            f"\n  Processing section: "
            f"{section}"
        )

        report, inserted_count = (
            insert_visualizations_into_section(
                report,
                section,
                charts
            )
        )

        total_inserted += inserted_count

        for title, _ in charts:

            print(
                f"    ✓ {title}"
            )

    return (
        report,
        total_inserted
    )


# ============================================================
# VERIFY FINAL MARKDOWN
# ============================================================

def verify_final_report(
    report: str,
    plan: dict
):

    visualizations = plan.get(
        "visualizations",
        []
    )

    missing = []

    for index, visualization in enumerate(
        visualizations,
        start=1
    ):

        title = normalize_title(
            visualization.get(
                "title",
                f"Visualization {index}"
            )
        )

        filename = (
            resolve_visualization_filename(
                visualization,
                index
            )
        )

        relative_path = (
            f"visualizations/{filename}"
        )

        image_reference = (
            f"]({relative_path})"
        )

        if image_reference not in report:

            missing.append(
                title
            )

    if missing:

        print(
            "\n⚠ Final report verification "
            "found missing visualizations:"
        )

        for title in missing:

            print(
                f"  ✗ {title}"
            )

        return False

    print(
        "\n✓ Final report verification passed."
    )

    return True


# ============================================================
# REPORTLAB HELPERS
# ============================================================

def markdown_inline_to_reportlab(text: str) -> str:
    """
    Convert a subset of Markdown inline formatting
    into ReportLab-compatible XML.

    The converter is intentionally defensive because AI-generated
    Markdown may contain malformed or overlapping * / ** markers.
    """

    text = text.strip()

    # ------------------------------------------------------------
    # 1. Escape XML first
    # ------------------------------------------------------------
    text = html.escape(text, quote=False)

    # ------------------------------------------------------------
    # 2. Inline code
    # ------------------------------------------------------------
    # Convert inline code before bold/italic processing so that
    # Markdown-like characters inside code are not interpreted.
    placeholders = {}

    def store_placeholder(match):
        key = f"@@INLINE_CODE_{len(placeholders)}@@"
        placeholders[key] = (
            "<font name='Courier'>"
            + match.group(1)
            + "</font>"
        )
        return key

    text = re.sub(
        r"`([^`]+)`",
        store_placeholder,
        text
    )

    # ------------------------------------------------------------
    # 3. Normalize common malformed AI Markdown
    # ------------------------------------------------------------
    # Example:
    # **DAILY*REVENUE**
    #
    # This can otherwise produce:
    # <b>DAILY<i>REVENUE</b>
    #
    # Remove the overlapping single * inside a **...** expression.
    text = re.sub(
        r"\*\*([^*\n]+)\*([^*\n]+)\*\*",
        r"**\1\2**",
        text
    )

    # ------------------------------------------------------------
    # 4. Bold + Italic
    # ------------------------------------------------------------
    text = re.sub(
        r"\*\*\*([^*\n]+)\*\*\*",
        r"<b><i>\1</i></b>",
        text
    )

    # ------------------------------------------------------------
    # 5. Bold
    # ------------------------------------------------------------
    text = re.sub(
        r"\*\*([^*\n]+)\*\*",
        r"<b>\1</b>",
        text
    )

    # ------------------------------------------------------------
    # 6. Italic
    # ------------------------------------------------------------
    text = re.sub(
        r"(?<!\*)\*([^*\n]+)\*(?!\*)",
        r"<i>\1</i>",
        text
    )

    # ------------------------------------------------------------
    # 7. Restore inline code
    # ------------------------------------------------------------
    for key, value in placeholders.items():
        text = text.replace(key, value)

    # ------------------------------------------------------------
    # 8. Defensive cleanup
    # ------------------------------------------------------------
    # AI-generated Markdown can occasionally contain malformed
    # combinations of formatting markers. Make sure we never
    # return raw Markdown stars that could interact badly with
    # ReportLab XML parsing.
    text = text.replace("**", "")
    
    return text


def is_markdown_table_separator(line: str) -> bool:
    """
    Detect Markdown table separator:
    | --- | --- |
    """

    stripped = line.strip()

    if "|" not in stripped:
        return False

    cells = [
        cell.strip()
        for cell in stripped.strip("|").split("|")
    ]

    if not cells:
        return False

    return all(
        re.fullmatch(
            r":?-{3,}:?",
            cell
        )
        for cell in cells
    )


def split_markdown_table_row(line: str):
    """
    Convert a Markdown table row into cells.
    """

    stripped = line.strip()

    if stripped.startswith("|"):
        stripped = stripped[1:]

    if stripped.endswith("|"):
        stripped = stripped[:-1]

    return [
        cell.strip()
        for cell in stripped.split("|")
    ]


def build_reportlab_table(
    table_lines,
    styles
):
    """
    Convert Markdown table lines into ReportLab Table.
    """

    rows = []

    for line in table_lines:

        if is_markdown_table_separator(line):
            continue

        cells = split_markdown_table_row(line)

        row = []

        for cell in cells:

            cell_text = (
                markdown_inline_to_reportlab(
                    cell
                )
            )

            row.append(
                Paragraph(
                    cell_text,
                    styles["TableCell"]
                )
            )

        rows.append(row)

    if not rows:
        return None

    max_columns = max(
        len(row)
        for row in rows
    )

    normalized_rows = []

    for row in rows:

        while len(row) < max_columns:

            row.append(
                Paragraph(
                    "",
                    styles["TableCell"]
                )
            )

        normalized_rows.append(row)

    available_width = (
        A4[0] - 3 * cm
    )

    table = Table(
        normalized_rows,
        colWidths=[
            available_width / max_columns
        ] * max_columns,
        repeatRows=1,
        hAlign="LEFT"
    )

    table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#E9EEF5")
                ),
                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#1F2937")
                ),
                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold"
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.4,
                    colors.HexColor("#B8C0CC")
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "TOP"
                ),
                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    5
                ),
                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    5
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    5
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    5
                ),
            ]
        )
    )

    return table


# ============================================================
# PAGE HEADER / FOOTER
# ============================================================

def draw_page_header_footer(
    canvas,
    document
):

    canvas.saveState()

    width, height = A4

    # Header
    canvas.setFont(
        "Helvetica",
        7.5
    )

    canvas.setFillColor(
        colors.HexColor("#6B7280")
    )

    canvas.drawString(
        1.5 * cm,
        height - 0.9 * cm,
        "AI Business Intelligence Report"
    )

    # Footer
    canvas.drawRightString(
        width - 1.5 * cm,
        0.8 * cm,
        f"Page {document.page}"
    )

    canvas.restoreState()


# ============================================================
# MARKDOWN → REPORTLAB PDF
# ============================================================

def markdown_to_pdf(
    markdown_text: str,
    output_pdf: Path
):
    """
    Convert integrated Markdown report into
    a professional PDF using ReportLab.

    Supports:
        # headings
        ## headings
        ### headings
        **bold**
        *italic*
        `inline code`
        bullet lists
        numbered lists
        horizontal rules
        Markdown images
        Markdown tables
        normal paragraphs
    """

    styles = getSampleStyleSheet()

    # --------------------------------------------------------
    # Custom styles
    # --------------------------------------------------------

    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        alignment=TA_CENTER,
        spaceBefore=8,
        spaceAfter=18
    )

    h1_style = ParagraphStyle(
        "H1Custom",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=17,
        leading=21,
        spaceBefore=18,
        spaceAfter=10,
        keepWithNext=True
    )

    h2_style = ParagraphStyle(
        "H2Custom",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        spaceBefore=14,
        spaceAfter=8,
        keepWithNext=True
    )

    h3_style = ParagraphStyle(
        "H3Custom",
        parent=styles["Heading3"],
        fontName="Helvetica-Bold",
        fontSize=11.5,
        leading=15,
        spaceBefore=10,
        spaceAfter=7,
        keepWithNext=True
    )

    body_style = ParagraphStyle(
        "BodyCustom",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=14,
        alignment=TA_LEFT,
        spaceAfter=8
    )

    bullet_style = ParagraphStyle(
        "BulletCustom",
        parent=body_style,
        leftIndent=15,
        firstLineIndent=-8,
        spaceAfter=4
    )

    numbered_style = ParagraphStyle(
        "NumberedCustom",
        parent=body_style,
        leftIndent=18,
        firstLineIndent=-10,
        spaceAfter=4
    )

    table_cell_style = ParagraphStyle(
        "TableCell",
        parent=body_style,
        fontSize=8,
        leading=10,
        spaceAfter=0
    )

    styles.add(
        table_cell_style
    )

    document = SimpleDocTemplate(
        str(output_pdf),
        pagesize=A4,
        rightMargin=1.5 * cm,
        leftMargin=1.5 * cm,
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm + 0.4 * cm,
        title="AI Business Intelligence Report",
        author="AI Business Analytics Pipeline"
    )

    story = []

    lines = markdown_text.splitlines()

    paragraph_buffer = []

    # --------------------------------------------------------
    # Flush paragraph
    # --------------------------------------------------------

    def flush_paragraph():

        if not paragraph_buffer:
            return

        text = " ".join(
            line.strip()
            for line in paragraph_buffer
        ).strip()

        if text:

            converted = (
                markdown_inline_to_reportlab(
                    text
                )
            )

            story.append(
                Paragraph(
                    converted,
                    body_style
                )
            )

        paragraph_buffer.clear()

    # --------------------------------------------------------
    # Process lines
    # --------------------------------------------------------

    index = 0

    while index < len(lines):

        line = lines[index]

        stripped = line.strip()

        # ----------------------------------------------------
        # Empty line
        # ----------------------------------------------------

        if not stripped:

            flush_paragraph()

            index += 1

            continue

        # ----------------------------------------------------
        # Markdown table
        # ----------------------------------------------------

        if (
            "|" in stripped
            and index + 1 < len(lines)
            and is_markdown_table_separator(
                lines[index + 1]
            )
        ):

            flush_paragraph()

            table_lines = [
                stripped
            ]

            index += 1

            while index < len(lines):

                current = lines[index].strip()

                if (
                    not current
                    or "|" not in current
                ):
                    break

                table_lines.append(
                    current
                )

                index += 1

            table = build_reportlab_table(
                table_lines,
                styles
            )

            if table:

                story.append(
                    Spacer(
                        1,
                        0.12 * cm
                    )
                )

                story.append(
                    table
                )

                story.append(
                    Spacer(
                        1,
                        0.25 * cm
                    )
                )

            continue

        # ----------------------------------------------------
        # Markdown image
        # ----------------------------------------------------

        image_match = re.match(
            r"!\[[^\]]*\]\(([^)]+)\)",
            stripped
        )

        if image_match:

            flush_paragraph()

            image_relative_path = (
                image_match.group(1)
            )

            image_path = (
                OUTPUT_DIR
                / image_relative_path
            )

            if image_path.exists():

                image = Image(
                    str(image_path)
                )

                max_width = (
                    A4[0] - 3 * cm
                )

                max_height = (
                    10 * cm
                )

                if image.imageWidth > 0:
                    width_scale = (
                        max_width
                        / image.imageWidth
                    )
                else:
                    width_scale = 1

                if image.imageHeight > 0:
                    height_scale = (
                        max_height
                        / image.imageHeight
                    )
                else:
                    height_scale = 1

                scale = min(
                    width_scale,
                    height_scale,
                    1.0
                )

                image.drawWidth = (
                    image.imageWidth * scale
                )

                image.drawHeight = (
                    image.imageHeight * scale
                )

                story.append(
                    Spacer(
                        1,
                        0.2 * cm
                    )
                )

                story.append(
                    image
                )

                story.append(
                    Spacer(
                        1,
                        0.3 * cm
                    )
                )

            else:

                print(
                    f"⚠ PDF image not found: "
                    f"{image_path}"
                )

            index += 1

            continue

        # ----------------------------------------------------
        # H1
        # ----------------------------------------------------

        if stripped.startswith("# "):

            flush_paragraph()

            text = stripped[2:].strip()

            converted = (
                markdown_inline_to_reportlab(
                    text
                )
            )

            story.append(
                Paragraph(
                    converted,
                    h1_style
                )
            )

            index += 1

            continue

        # ----------------------------------------------------
        # H2
        # ----------------------------------------------------

        if stripped.startswith("## "):

            flush_paragraph()

            text = stripped[3:].strip()

            converted = (
                markdown_inline_to_reportlab(
                    text
                )
            )

            story.append(
                Paragraph(
                    converted,
                    h2_style
                )
            )

            index += 1

            continue

        # ----------------------------------------------------
        # H3
        # ----------------------------------------------------

        if stripped.startswith("### "):

            flush_paragraph()

            text = stripped[4:].strip()

            converted = (
                markdown_inline_to_reportlab(
                    text
                )
            )

            story.append(
                Paragraph(
                    converted,
                    h3_style
                )
            )

            index += 1

            continue

        # ----------------------------------------------------
        # Horizontal rule
        # ----------------------------------------------------

        if stripped in (
            "---",
            "***",
            "___"
        ):

            flush_paragraph()

            story.append(
                Spacer(
                    1,
                    0.15 * cm
                )
            )

            index += 1

            continue

        # ----------------------------------------------------
        # Bullet
        # ----------------------------------------------------

        if (
            stripped.startswith("* ")
            or stripped.startswith("- ")
            or stripped.startswith("• ")
        ):

            flush_paragraph()

            if stripped.startswith("• "):

                text = stripped[2:].strip()

            else:

                text = stripped[2:].strip()

            converted = (
                markdown_inline_to_reportlab(
                    text
                )
            )

            story.append(
                Paragraph(
                    f"• {converted}",
                    bullet_style
                )
            )

            index += 1

            continue

        # ----------------------------------------------------
        # Numbered list
        # ----------------------------------------------------

        numbered_match = re.match(
            r"^(\d+)\.\s+(.+)$",
            stripped
        )

        if numbered_match:

            flush_paragraph()

            number = (
                numbered_match.group(1)
            )

            text = (
                numbered_match.group(2)
            )

            converted = (
                markdown_inline_to_reportlab(
                    text
                )
            )

            story.append(
                Paragraph(
                    f"{number}. {converted}",
                    numbered_style
                )
            )

            index += 1

            continue

        # ----------------------------------------------------
        # Normal paragraph
        # ----------------------------------------------------

        paragraph_buffer.append(
            stripped
        )

        index += 1

    # --------------------------------------------------------
    # Flush final paragraph
    # --------------------------------------------------------

    flush_paragraph()

    # --------------------------------------------------------
    # Build PDF
    # --------------------------------------------------------

    document.build(
        story,
        onFirstPage=draw_page_header_footer,
        onLaterPages=draw_page_header_footer
    )


# ============================================================
# MAIN
# ============================================================

def main():

    print("=" * 70)

    print(
        "AI BUSINESS REPORT "
        "VISUAL INTEGRATOR + PDF GENERATOR"
    )

    print("=" * 70)

    # --------------------------------------------------------
    # [1/8] Load report
    # --------------------------------------------------------

    print(
        "\n[1/8] Loading existing business report..."
    )

    report = load_report(
        REPORT_FILE
    )

    print(
        "✓ Loaded: ai_business_report.md"
    )

    # --------------------------------------------------------
    # [2/8] Load visualization plan
    # --------------------------------------------------------

    print(
        "\n[2/8] Loading visualization plan..."
    )

    plan = load_json(
        VISUALIZATION_PLAN_FILE
    )

    visualizations = plan.get(
        "visualizations",
        []
    )

    print(
        f"✓ Found {len(visualizations)} "
        "visualizations."
    )

    # --------------------------------------------------------
    # [3/8] Validation
    # --------------------------------------------------------

    print(
        "\n[3/8] Checking visualization validation..."
    )

    validation = load_json(
        VISUALIZATION_VALIDATION_FILE
    )

    check_validation(
        validation
    )

    # --------------------------------------------------------
    # [4/8] Check PNG files
    # --------------------------------------------------------

    print(
        "\n[4/8] Checking generated visualization files..."
    )

    check_visualization_files(
        plan
    )

    # --------------------------------------------------------
    # Clean report
    # --------------------------------------------------------

    print(
        "\nCleaning existing visualization blocks..."
    )

    report = (
        remove_existing_visualization_blocks(
            report
        )
    )

    report = (
        clean_markdown_formatting(
            report
        )
    )

    # --------------------------------------------------------
    # [5/8] Integrate visuals
    # --------------------------------------------------------

    print(
        "\n[5/8] Integrating visualizations..."
    )

    report, inserted_count = (
        integrate_visualizations(
            report,
            plan
        )
    )

    # --------------------------------------------------------
    # [6/8] Verify Markdown
    # --------------------------------------------------------

    print(
        "\n[6/8] Verifying integrated report..."
    )

    verification_passed = (
        verify_final_report(
            report,
            plan
        )
    )

    if not verification_passed:

        raise RuntimeError(
            "Final report verification failed."
        )

    # --------------------------------------------------------
    # Save Markdown
    # --------------------------------------------------------

    FINAL_REPORT_FILE.write_text(
        report,
        encoding="utf-8"
    )

    print(
        f"✓ Saved Markdown report:"
        f"\n  {FINAL_REPORT_FILE}"
    )

    # --------------------------------------------------------
    # [7/8] Generate PDF
    # --------------------------------------------------------

    print(
        "\n[7/8] Generating final PDF..."
    )

    markdown_to_pdf(
        report,
        FINAL_PDF_FILE
    )

    print(
        f"✓ PDF generated:"
        f"\n  {FINAL_PDF_FILE}"
    )

    # --------------------------------------------------------
    # [8/8] Final summary
    # --------------------------------------------------------

    print(
        "\n[8/8] Final summary..."
    )

    print(
        "\n" + "=" * 70
    )

    print(
        "FINAL REPORT SUMMARY"
    )

    print(
        "=" * 70
    )

    print(
        f"Visualizations planned : "
        f"{len(visualizations)}"
    )

    print(
        f"Visualizations inserted: "
        f"{inserted_count}"
    )

    print(
        "Visualization verification: PASSED"
    )

    print(
        "PDF generation: PASSED"
    )

    print(
        "\nOriginal Markdown:"
    )

    print(
        REPORT_FILE
    )

    print(
        "\nIntegrated Markdown:"
    )

    print(
        FINAL_REPORT_FILE
    )

    print(
        "\nFinal PDF:"
    )

    print(
        FINAL_PDF_FILE
    )

    print(
        "=" * 70
    )

    print(
        "\nAI_BUSINESS_REPORT_FINAL_COMPLETE"
    )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":

    try:

        main()

    except Exception as error:

        print(
            "\nERROR:"
        )

        print(
            error
        )

        sys.exit(1)