import json
import time
from pathlib import Path

from google import genai
from google.genai import types

from src.config import GEMINI_API_KEY


# ================================================================
# WEEK 10 - AI FOR BI & DATA ANALYTICS
# AI SQL GENERATOR
# ================================================================


# ================================================================
# PATHS
# ================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

PLAN_FILE = BASE_DIR / "output" / "analysis_plan.json"
PROMPT_FILE = BASE_DIR / "prompts" / "sql_generator_prompt.md"
OUTPUT_FILE = BASE_DIR / "output" / "generated_sql.json"


# ================================================================
# GEMINI
# ================================================================

MODEL_NAME = "gemini-3.6-flash"

client = genai.Client(
    api_key=GEMINI_API_KEY,
    http_options=types.HttpOptions(
        retry_options=types.HttpRetryOptions(
            attempts=1
        )
    )
)


# ================================================================
# LOAD FILE
# ================================================================

def load_text_file(file_path: Path) -> str:

    if not file_path.exists():
        raise FileNotFoundError(
            f"File not found: {file_path}"
        )

    with open(
        file_path,
        "r",
        encoding="utf-8"
    ) as file:

        return file.read()


# ================================================================
# LOAD ANALYSIS PLAN
# ================================================================

def load_analysis_plan() -> dict:

    if not PLAN_FILE.exists():
        raise FileNotFoundError(
            f"Analysis plan not found: {PLAN_FILE}"
        )

    with open(
        PLAN_FILE,
        "r",
        encoding="utf-8"
    ) as file:

        plan = json.load(file)

    required_fields = {
        "business_question",
        "analysis_type",
        "dimensions",
        "kpis",
        "top_n",
    }

    missing_fields = required_fields - set(plan.keys())

    if missing_fields:
        raise ValueError(
            "Analysis plan is missing required fields: "
            + ", ".join(sorted(missing_fields))
        )

    return plan


# ================================================================
# BUILD PROMPT
# ================================================================

def build_prompt(
    template: str,
    plan: dict
) -> str:

    plan_json = json.dumps(
        plan,
        indent=4,
        ensure_ascii=False
    )

    return f"""
{template}

============================================================
VALIDATED ANALYSIS PLAN
============================================================

The following analysis plan was generated by the Planner
and is considered validated input.

Do NOT change the business question.

Do NOT invent additional dimensions.

Do NOT invent KPIs.

Use this plan to generate the analytical SQL.

{plan_json}

============================================================
END OF ANALYSIS PLAN
============================================================

Return JSON only.
"""


# ================================================================
# PARSE GEMINI RESPONSE
# ================================================================

def parse_response(response_text: str) -> dict:

    if not response_text:
        raise ValueError(
            "Gemini returned an empty response."
        )

    text = response_text.strip()

    # ------------------------------------------------------------
    # Remove accidental Markdown code fences
    # ------------------------------------------------------------

    if text.startswith("```"):

        lines = text.splitlines()

        if lines and lines[0].strip().startswith("```"):
            lines = lines[1:]

        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]

        text = "\n".join(lines).strip()

    # ------------------------------------------------------------
    # Parse JSON
    # ------------------------------------------------------------

    try:

        data = json.loads(text)

    except json.JSONDecodeError as exc:

        raise ValueError(
            "Gemini did not return valid JSON."
        ) from exc

    # ------------------------------------------------------------
    # Validate structure
    # ------------------------------------------------------------

    if not isinstance(data, dict):

        raise ValueError(
            "Generated SQL response must be a JSON object."
        )

    if "queries" not in data:

        raise ValueError(
            "Generated SQL response is missing 'queries'."
        )

    queries = data["queries"]

    if not isinstance(queries, list):

        raise ValueError(
            "'queries' must be a list."
        )

    if not queries:

        raise ValueError(
            "Gemini returned an empty query list."
        )

    for index, query in enumerate(queries, start=1):

        if not isinstance(query, dict):

            raise ValueError(
                f"Query {index} must be a JSON object."
            )

        required_fields = {
            "name",
            "purpose",
            "sql",
        }

        missing_fields = (
            required_fields - set(query.keys())
        )

        if missing_fields:

            raise ValueError(
                f"Query {index} is missing fields: "
                + ", ".join(sorted(missing_fields))
            )

        if not isinstance(query["sql"], str):

            raise ValueError(
                f"SQL for query {index} must be a string."
            )

        if not query["sql"].strip():

            raise ValueError(
                f"SQL for query {index} is empty."
            )

    return data


# ================================================================
# SAVE GENERATED SQL
# ================================================================

def save_generated_sql(
    plan: dict,
    generated_sql: dict
):

    OUTPUT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    output = {
        "business_question": plan[
            "business_question"
        ],
        "analysis_type": plan[
            "analysis_type"
        ],
        "dimensions": plan[
            "dimensions"
        ],
        "kpis": plan[
            "kpis"
        ],
        "top_n": plan[
            "top_n"
        ],
        "queries": generated_sql[
            "queries"
        ],
    }

    with open(
        OUTPUT_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            output,
            file,
            indent=4,
            ensure_ascii=False
        )

    print(
        f"\nGenerated SQL saved to:\n{OUTPUT_FILE}"
    )


# ================================================================
# GEMINI RETRY HANDLER
# ================================================================

def generate_with_retry(
    client,
    model,
    prompt,
    max_retries=4,
):
    """
    Generate Gemini content with controlled retry behavior.

    Retry policy:

    - 503 / UNAVAILABLE:
        Retry with exponential backoff.

    - 429 / RESOURCE_EXHAUSTED:
        Stop immediately.
        Do NOT retry because this usually indicates
        that the Gemini quota has been exhausted.

    - Other errors:
        Stop immediately.

    Retry delays for temporary 503 errors:

        Attempt 1 -> 1 second
        Attempt 2 -> 2 seconds
        Attempt 3 -> 4 seconds
    """

    for attempt in range(max_retries):

        try:

            print(
                f"\nGemini request attempt "
                f"{attempt + 1}/{max_retries}..."
            )

            response = client.models.generate_content(
                model=model,
                contents=prompt,
            )

            print("Gemini response received.")

            return response

        except Exception as exc:

            error_message = str(exc)

            # ----------------------------------------------------
            # QUOTA EXCEEDED
            # ----------------------------------------------------
            # Do NOT retry 429 errors.
            #
            # The SDK itself is also configured with attempts=1,
            # so there is no hidden internal retry.
            # ----------------------------------------------------

            is_quota_error = (
                "429" in error_message
                or "RESOURCE_EXHAUSTED" in error_message
            )

            if is_quota_error:

                print(
                    "\nGemini quota exceeded."
                )

                print(
                    "Stopping immediately without retry."
                )

                print(
                    "Please wait for the quota to reset "
                    "or check your Gemini API plan/billing."
                )

                raise

            # ----------------------------------------------------
            # TEMPORARY SERVICE ERROR
            # ----------------------------------------------------

            is_service_unavailable = (
                "503" in error_message
                or "UNAVAILABLE" in error_message
            )

            if is_service_unavailable:

                # ------------------------------------------------
                # No retries left
                # ------------------------------------------------

                if attempt == max_retries - 1:

                    print(
                        "\nGemini request failed after "
                        f"{max_retries} attempts."
                    )

                    raise

                # ------------------------------------------------
                # Exponential backoff
                # ------------------------------------------------

                wait_seconds = 2 ** attempt

                print(
                    "\nGemini service is temporarily unavailable."
                )

                print(
                    f"Retrying in {wait_seconds} seconds..."
                )

                time.sleep(wait_seconds)

                continue

            # ----------------------------------------------------
            # UNKNOWN / NON-RETRYABLE ERROR
            # ----------------------------------------------------

            raise


# ================================================================
# GENERATE SQL
# ================================================================

def generate_sql():

    print()
    print("=" * 70)
    print("WEEK 10 - AI SQL GENERATOR")
    print("=" * 70)

    print("\n[1/4] Loading analysis plan...")

    plan = load_analysis_plan()

    print(
        f"Analysis type: {plan['analysis_type']}"
    )

    print(
        f"KPIs: {', '.join(plan['kpis'])}"
    )

    print(
        f"Top N: {plan['top_n']}"
    )

    print("\n[2/4] Loading SQL generator prompt...")

    prompt_template = load_text_file(
        PROMPT_FILE
    )

    print(
        f"Prompt loaded from: {PROMPT_FILE}"
    )

    print(
        "\n[3/4] Sending schema + analysis plan to Gemini..."
    )

    prompt = build_prompt(
        prompt_template,
        plan
    )

    response = generate_with_retry(
        client=client,
        model=MODEL_NAME,
        prompt=prompt,
    )

    if not response.text:

        raise ValueError(
            "Gemini returned an empty response."
        )

    print(
        "\nGemini response received."
    )

    generated_sql = parse_response(
        response.text
    )

    print(
        f"Generated queries: "
        f"{len(generated_sql['queries'])}"
    )

    print("\n[4/4] Saving generated SQL...")

    save_generated_sql(
        plan,
        generated_sql
    )

    print()
    print("=" * 70)
    print("AI SQL GENERATION COMPLETED")
    print("=" * 70)

    return generated_sql


# ================================================================
# ENTRY POINT
# ================================================================

if __name__ == "__main__":

    generate_sql()